CREATE DATABASE IF NOT EXISTS n2iioq4wv0qjb3cq;

USE n2iioq4wv0qjb3cq;

CREATE TABLE burgers (
    id INTEGER AUTO_INCREMENT NOT NULL,
    burger_name VARCHAR(256) NOT NULL,
    devoured BOOLEAN NOT NULL,
    PRIMARY KEY (id)
);